USE DataWarehouseAnalytics

-- Exploratory Data Analysis (EDA) 

SELECT *
FROM INFORMATION_SCHEMA.TABLES

SELECT * 
FROM INFORMATION_SCHEMA.COLUMNS 

SELECT * 
FROM gold.dim_customers

SELECT DISTINCT (country) 
FROM gold.dim_customers

-- Find the youngest & oldest customer with their age 
SELECT
	MIN(birthdate) AS Oldest_customer,
	DATEDIFF(YEAR, MIN(birthdate), GETDATE()) AS Age,
	MAX(birthdate) AS Youngest_customer, 
	DATEDIFF(YEAR, MAX(birthdate), GETDATE()) AS Age
FROM gold.dim_customers

SELECT * 
FROM gold.fact_sales

-- Find the total sales 
SELECT 
	SUM(sales_amount) AS total_sales
FROM gold.fact_sales

-- Find how many items are sold 
SELECT 
	SUM(quantity) AS items_sold
FROM gold.fact_sales

-- Find the average selling price 
SELECT 
	AVG(price) AS avg_price
FROM gold.fact_sales

-- Find the total number of orders 
SELECT 
	COUNT(order_number) AS total_orders
FROM gold.fact_sales

-- Find the total number of products 
SELECT 
	COUNT(DISTINCT(order_number)) AS total_orders
FROM gold.fact_sales

-- Find the total number of customers 
SELECT 
	COUNT(DISTINCT(customer_id)) AS #customers
FROM gold.dim_customers

-- Find the total number of customers that has placed an order 
SELECT 
	COUNT(DISTINCT(customer_key)) AS #customers_placed_orders
FROM gold.fact_sales

-- Report view
SELECT 
	'total_sales' as measure_name,
	SUM(sales_amount) AS total_sales
FROM gold.fact_sales
UNION ALL 
SELECT 'items_sold' ,SUM(quantity) AS items_sold
FROM gold.fact_sales
UNION ALL 
SELECT '#customers' ,COUNT(DISTINCT(customer_id)) AS #customers
FROM gold.dim_customers


-- Find total customers by countries 
SELECT 
	country, 
	COUNT(customer_key) As total_customers 
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

-- Find total customers by gender 
SELECT 
	gender, 
	COUNT(customer_key) As total_customers 
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

-- Find total products by category 
SELECT 
	category, 
	COUNT(product_id) As total_orders 
FROM gold.dim_products
GROUP BY category
ORDER BY total_orders DESC

-- What is the average costs in each category 
SELECT 
	category, 
	AVG(s.price) As total_costs 
FROM gold.dim_products AS p
JOIN gold.fact_sales AS s
ON p.product_key = s.product_key
GROUP BY category
ORDER BY total_costs DESC

-- What is the total revenue generated by each customer 
SELECT 
	p.category, 
	SUM(s.sales_amount) AS total_sales
FROM gold.dim_products AS p
LEFT JOIN gold.fact_sales AS s 
ON p.product_key = s.product_key
GROUP BY category
ORDER BY total_sales DESC

-- Find total revenue is generated by each customer 
SELECT 
	c.customer_id, 
	c.first_name, 
	c.last_name, 
	c.country, 
	SUM(s.sales_amount) AS total_sales
FROM gold.dim_customers AS c
LEFT JOIN gold.fact_sales AS s
ON c.customer_key = s.customer_key
GROUP BY c.customer_id, 
	c.first_name, 
	c.last_name, 
	c.country 
ORDER BY total_sales DESC

-- What is the distribution of sold items across countries 
SELECT 
	c.country, 
	SUM(s.quantity) AS #sold_items
FROM gold.dim_customers AS c 
JOIN gold.fact_sales AS s
ON c.customer_key = s.customer_key
GROUP BY c.country
ORDER BY #sold_items DESC

-- Which 5 products generate the highest revenue 
SELECT TOP 5
	p.product_name, 
	SUM(s.sales_amount) AS revenue 
FROM gold.dim_products AS p
JOIN gold.fact_sales AS s
ON p.product_key = s.product_key
GROUP BY P.product_name
ORDER BY revenue DESC

-- another solution with rank & subquery 

-- Which 5 products generate the highest revenue 
SELECT *
FROM(
	SELECT 
	p.product_name, 
	SUM(s.sales_amount) AS revenue,
	RANK() OVER (ORDER BY SUM(s.sales_amount) DESC ) AS rank_products
FROM gold.dim_products AS p
JOIN gold.fact_sales AS s
ON p.product_key = s.product_key
GROUP BY P.product_name) t
WHERE rank_products <= 5

-- What are the 5 worst-performing products in items of sales
SELECT TOP 5
	p.product_name, 
	SUM(s.sales_amount) AS revenue 
FROM gold.dim_products AS p
JOIN gold.fact_sales AS s
ON p.product_key = s.product_key
GROUP BY P.product_name
ORDER BY revenue

-- Find the 3 customers with the fewest orders placed 
SELECT TOP 3
	c.customer_key,
	c.first_name, 
	c.last_name, 
	COUNT(DISTINCT(s.order_number)) AS total_orders
FROM gold.dim_customers AS c
LEFT JOIN gold.fact_sales AS s 
ON c.customer_key = s.customer_key
GROUP BY 
	c.customer_key,
	c.first_name, 
	c.last_name 
ORDER BY total_orders 

-- Find the orders with price higher than the average price 
SELECT 
*
FROM
(
	SELECT 
		product_key, price,
		AVG(price) OVER() avg_price 
	FROM gold.fact_sales) a
	WHERE price > avg_price

-- Rank the customers based on their total sales
SELECT *, 
RANK () OVER (ORDER BY total_sales DESC) customer_rank
FROM 
	(SELECT 
	customer_key, 
	SUM(sales_amount) AS total_sales
	FROM gold.fact_sales 
	GROUP BY customer_key) s